apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - './infra/k8s/*'
build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: seventh-hallway-391612
  artifacts:
    # - image: leonyalin/client
    #   context: ./client
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: "src/**/*.js"
    #         dest: .
    # - image: us.gcr.io/seventh-hallway-391612/auth
    - image: leonyalin/auth
      context: ./auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: leonyalin/client
      context: ./client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
